export type Language = 'en' | 'hi' | 'kn' | 'ta' | 'te';

export const PRIMARY_LANGUAGES: Language[] = ['en', 'hi', 'kn'];
export const MORE_LANGUAGES: Language[] = ['ta', 'te'];

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: 'EN',
  hi: 'हिं',
  kn: 'ಕ',
  ta: 'த',
  te: 'తె',
};

export const LANGUAGE_NAMES: Record<Language, string> = {
  en: 'English',
  hi: 'हिंदी',
  kn: 'ಕನ್ನಡ',
  ta: 'தமிழ்',
  te: 'తెలుగు',
};

const enStrings = {
    ask_sentinel: 'Ask Prahari',
    all_systems_operational: 'All systems operational',
    n_devices_flagged: '{n} devices flagged',
    network_trust: 'Network Trust',
    devices_monitored: 'Devices Monitored',
    active_incidents: 'Active Incidents',
    fleet: 'Fleet',
    healthy: 'Healthy',
    watch: 'Watch',
    at_risk: 'At Risk',
    critical: 'Critical',
    risk: 'Risk',
    back_to_fleet: 'Fleet',
    evidence: 'Evidence',
    top_deviations: 'Top Deviations',
    drift_signals: 'Drift Signals',
    window: 'Window',
    timestamp: 'Timestamp',
    behavioral_heatmap: 'Behavioral Heatmap',
    trust_timeline: 'Trust Timeline',
    drift_signal_stack: 'Drift Signal Stack',
    generate_block_script: 'Generate Block Script',
    generate_playbook: 'Generate Playbook',
    download_report: 'Download Report',
    mark_investigated: 'Mark Investigated',
    ask_anything: 'Ask anything about your network',
    ask_placeholder: 'Ask Prahari anything...',
    translate: 'Translate',
    regenerate: 'Regenerate',
    ask_followup: 'Ask Follow-up',
    sentinel_analyst: 'Prahari Analyst',
    sending: 'Sending',
    consulting_evidence: 'Consulting evidence',
    checking_peers: 'Checking peers',
    consulted: 'consulted',
    consulting: 'consulting',
    sentinel_analyzing: 'Prahari is analyzing',
    stream_connected: 'Stream: connected',
    reconnecting: 'Reconnecting',
    updated_n_ago: 'Updated {n}s ago',
    scenario: 'Scenario',
    scenario_live: 'Live Network',
    scenario_slow_drift: 'Slow Drift Pattern',
    scenario_sudden_ddos: 'Sudden DDoS Attack',
    scenario_recon_scan: 'Reconnaissance Scan',
    press_to_initialize: 'Press to initialize',
    press_to_discover: 'Press to discover',
    press_to_lock: 'Press to lock',
    sentinel_ready: 'Prahari ready',
    press_to_enter: 'Press to enter',
    skip_intro: 'Skip intro',
    more_languages: 'More languages',
    baseline_locked: 'Baseline locked',
    drift_status: 'Drift Status',
    drift_confirmed: 'Drift Confirmed',
    stable: 'Stable',
    analyst_note: 'Prahari · Analyst Note',
    no_active_threats: 'No active threats detected',
    anomalous_behavior: 'Anomalous behavior detected',
    trust_score: 'Trust score',
    last_60_windows: 'Last 60 windows',
    last_30_windows: 'Last 30 windows',
    z_score_deviations: 'Z-score deviations · 22 features',
    feature: 'Feature',
    z_score: 'Z-score',
    nominal: 'Nominal',
    deviating: 'Deviating',
    high: 'High',
    inactive: 'Inactive',
    active: 'Active',
    none_fired: 'None fired',
    enter_to_send: 'Enter to send · Shift + Enter for newline',
    sarvam_on: 'Sarvam · ON',
    sarvam_degraded: 'Sarvam · DEGRADED',
    sarvam_offline: 'Sarvam · OFFLINE',
    device_not_found: 'Device not found',
    default_summary: 'Prahari is currently analyzing the recent traffic patterns for this device to determine the root cause of the current trust trajectory.',
    prompt_worry: 'What should I worry about?',
    prompt_unusual: 'Show me unusual activity in the last hour',
    prompt_health: 'Summarize current network health',
};

export const strings = {
  en: enStrings,
  hi: {
    ask_sentinel: 'Prahari से पूछें',
    all_systems_operational: 'सभी सिस्टम सामान्य हैं',
    n_devices_flagged: '{n} डिवाइस चिन्हित',
    network_trust: 'नेटवर्क विश्वास',
    devices_monitored: 'निगरानी में डिवाइस',
    active_incidents: 'सक्रिय घटनाएं',
    fleet: 'फ्लीट',
    healthy: 'स्वस्थ',
    watch: 'निगरानी',
    at_risk: 'जोखिम',
    critical: 'गंभीर',
    risk: 'जोखिम',
    back_to_fleet: 'फ्लीट',
    evidence: 'साक्ष्य',
    top_deviations: 'मुख्य विचलन',
    drift_signals: 'Drift संकेत',
    window: 'विंडो',
    timestamp: 'समय',
    behavioral_heatmap: 'व्यवहार हीटमैप',
    trust_timeline: 'विश्वास समयरेखा',
    drift_signal_stack: 'Drift संकेत स्टैक',
    generate_block_script: 'Block Script बनाएं',
    generate_playbook: 'Playbook बनाएं',
    download_report: 'रिपोर्ट डाउनलोड करें',
    mark_investigated: 'जांच पूर्ण चिह्नित करें',
    ask_anything: 'अपने नेटवर्क के बारे में कुछ भी पूछें',
    ask_placeholder: 'Prahari से कुछ भी पूछें...',
    translate: 'अनुवाद करें',
    regenerate: 'फिर से बनाएं',
    ask_followup: 'Follow-up पूछें',
    sentinel_analyst: 'Prahari विश्लेषक',
    sending: 'भेज रहे हैं',
    consulting_evidence: 'साक्ष्य देख रहा है',
    checking_peers: 'Peers जांच रहा है',
    consulted: 'देख लिया',
    consulting: 'देख रहा है',
    sentinel_analyzing: 'Prahari विश्लेषण कर रहा है',
    stream_connected: 'स्ट्रीम: कनेक्टेड',
    reconnecting: 'फिर से कनेक्ट हो रहा है',
    updated_n_ago: '{n}s पहले अपडेट',
    scenario: 'परिदृश्य',
    scenario_live: 'लाइव नेटवर्क',
    scenario_slow_drift: 'धीमा Drift पैटर्न',
    scenario_sudden_ddos: 'अचानक DDoS हमला',
    scenario_recon_scan: 'Reconnaissance Scan',
    press_to_initialize: 'शुरू करने के लिए दबाएं',
    press_to_discover: 'खोजने के लिए दबाएं',
    press_to_lock: 'Lock करने के लिए दबाएं',
    sentinel_ready: 'Prahari तैयार है',
    press_to_enter: 'प्रवेश के लिए दबाएं',
    skip_intro: 'Intro छोड़ें',
    more_languages: 'और भाषाएं',
    baseline_locked: 'Baseline locked',
    drift_status: 'Drift स्थिति',
    drift_confirmed: 'Drift पुष्टि',
    stable: 'स्थिर',
    analyst_note: 'Prahari · विश्लेषक नोट',
    no_active_threats: 'कोई सक्रिय खतरा नहीं',
    anomalous_behavior: 'असामान्य व्यवहार मिला',
    trust_score: 'विश्वास स्कोर',
    last_60_windows: 'पिछली 60 विंडो',
    last_30_windows: 'पिछली 30 विंडो',
    z_score_deviations: 'Z-score विचलन · 22 features',
    feature: 'Feature',
    z_score: 'Z-score',
    nominal: 'सामान्य',
    deviating: 'विचलित',
    high: 'उच्च',
    inactive: 'निष्क्रिय',
    active: 'सक्रिय',
    none_fired: 'कोई संकेत नहीं',
    enter_to_send: 'भेजने के लिए Enter · नई लाइन के लिए Shift + Enter',
    sarvam_on: 'Sarvam · ON',
    sarvam_degraded: 'Sarvam · DEGRADED',
    sarvam_offline: 'Sarvam · OFFLINE',
    device_not_found: 'डिवाइस नहीं मिला',
    default_summary: 'Prahari इस डिवाइस के हालिया traffic patterns का विश्लेषण कर रहा है ताकि मौजूदा trust trajectory का कारण पता चले.',
    prompt_worry: 'मुझे किस बात की चिंता करनी चाहिए?',
    prompt_unusual: 'पिछले घंटे की असामान्य activity दिखाएं',
    prompt_health: 'मौजूदा network health का सार बताएं',
  },
  kn: {
    ask_sentinel: 'Prahari ಗೆ ಕೇಳಿ',
    all_systems_operational: 'ಎಲ್ಲಾ ವ್ಯವಸ್ಥೆಗಳು ಸರಿಯಾಗಿವೆ',
    n_devices_flagged: '{n} ಸಾಧನಗಳು ಗುರುತಿಸಲಾಗಿದೆ',
    network_trust: 'ನೆಟ್‌ವರ್ಕ್ ವಿಶ್ವಾಸ',
    devices_monitored: 'ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿ ಸಾಧನಗಳು',
    active_incidents: 'ಸಕ್ರಿಯ ಘಟನೆಗಳು',
    fleet: 'ಸಾಧನಗಳು',
    healthy: 'ಆರೋಗ್ಯಕರ',
    watch: 'ಗಮನಿಸಿ',
    at_risk: 'ಅಪಾಯ',
    critical: 'ಗಂಭೀರ',
    risk: 'ಅಪಾಯ',
    back_to_fleet: 'ಸಾಧನಗಳು',
    evidence: 'ಪುರಾವೆ',
    top_deviations: 'ಮುಖ್ಯ ವಿಚಲನಗಳು',
    drift_signals: 'Drift ಸೂಚನೆಗಳು',
    window: 'ವಿಂಡೋ',
    timestamp: 'ಸಮಯ',
    behavioral_heatmap: 'ವರ್ತನೆ ಹೀಟ್‌ಮ್ಯಾಪ್',
    trust_timeline: 'ವಿಶ್ವಾಸ ಸಮಯಾವಧಿ',
    drift_signal_stack: 'Drift ಸೂಚನೆ ಸ್ಟ್ಯಾಕ್',
    generate_block_script: 'Block Script ರಚಿಸಿ',
    generate_playbook: 'Playbook ರಚಿಸಿ',
    download_report: 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    mark_investigated: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತು ಮಾಡಿ',
    ask_anything: 'ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ',
    ask_placeholder: 'Prahari ಗೆ ಏನಾದರೂ ಕೇಳಿ...',
    translate: 'ಅನುವಾದಿಸಿ',
    regenerate: 'ಮತ್ತೆ ರಚಿಸಿ',
    ask_followup: 'Follow-up ಕೇಳಿ',
    sentinel_analyst: 'Prahari ವಿಶ್ಲೇಷಕ',
    sending: 'ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ',
    consulting_evidence: 'ಪುರಾವೆ ನೋಡುತ್ತಿದೆ',
    checking_peers: 'Peers ಪರಿಶೀಲಿಸುತ್ತಿದೆ',
    consulted: 'ನೋಡಿದೆ',
    consulting: 'ನೋಡುತ್ತಿದೆ',
    sentinel_analyzing: 'Prahari ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ',
    stream_connected: 'ಸ್ಟ್ರೀಮ್: ಸಂಪರ್ಕಿತ',
    reconnecting: 'ಮತ್ತೆ ಸಂಪರ್ಕಿಸುತ್ತಿದೆ',
    updated_n_ago: '{n}s ಹಿಂದೆ ನವೀಕರಿಸಲಾಗಿದೆ',
    scenario: 'ಸನ್ನಿವೇಶ',
    scenario_live: 'ಲೈವ್ ನೆಟ್‌ವರ್ಕ್',
    scenario_slow_drift: 'ನಿಧಾನ Drift ಮಾದರಿ',
    scenario_sudden_ddos: 'ಅಕಸ್ಮಾತ್ DDoS ದಾಳಿ',
    scenario_recon_scan: 'Reconnaissance Scan',
    press_to_initialize: 'ಆರಂಭಿಸಲು ಒತ್ತಿ',
    press_to_discover: 'ಹುಡುಕಲು ಒತ್ತಿ',
    press_to_lock: 'Lock ಮಾಡಲು ಒತ್ತಿ',
    sentinel_ready: 'Prahari ಸಿದ್ಧವಾಗಿದೆ',
    press_to_enter: 'ಪ್ರವೇಶಿಸಲು ಒತ್ತಿ',
    skip_intro: 'Intro ಬಿಡಿ',
    more_languages: 'ಇನ್ನಷ್ಟು ಭಾಷೆಗಳು',
    baseline_locked: 'Baseline locked',
    drift_status: 'Drift ಸ್ಥಿತಿ',
    drift_confirmed: 'Drift ದೃಢಪಟ್ಟಿದೆ',
    stable: 'ಸ್ಥಿರ',
    analyst_note: 'Prahari · ವಿಶ್ಲೇಷಕ ಟಿಪ್ಪಣಿ',
    no_active_threats: 'ಸಕ್ರಿಯ ಬೆದರಿಕೆಗಳಿಲ್ಲ',
    anomalous_behavior: 'ಅಸಾಮಾನ್ಯ ವರ್ತನೆ ಕಂಡುಬಂದಿದೆ',
    trust_score: 'ವಿಶ್ವಾಸ ಸ್ಕೋರ್',
    last_60_windows: 'ಕೊನೆಯ 60 ವಿಂಡೋಗಳು',
    last_30_windows: 'ಕೊನೆಯ 30 ವಿಂಡೋಗಳು',
    z_score_deviations: 'Z-score ವಿಚಲನಗಳು · 22 features',
    feature: 'Feature',
    z_score: 'Z-score',
    nominal: 'ಸಾಮಾನ್ಯ',
    deviating: 'ವಿಚಲನ',
    high: 'ಹೆಚ್ಚು',
    inactive: 'ನಿಷ್ಕ್ರಿಯ',
    active: 'ಸಕ್ರಿಯ',
    none_fired: 'ಯಾವ ಸೂಚನೆಯೂ ಇಲ್ಲ',
    enter_to_send: 'ಕಳುಹಿಸಲು Enter · ಹೊಸ ಸಾಲಿಗೆ Shift + Enter',
    sarvam_on: 'Sarvam · ON',
    sarvam_degraded: 'Sarvam · DEGRADED',
    sarvam_offline: 'Sarvam · OFFLINE',
    device_not_found: 'ಸಾಧನ ಕಂಡುಬಂದಿಲ್ಲ',
    default_summary: 'Prahari ಈ ಸಾಧನದ ಇತ್ತೀಚಿನ traffic patterns ಅನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ, ಪ್ರಸ್ತುತ trust trajectory ಕಾರಣ ತಿಳಿಯಲು.',
    prompt_worry: 'ನಾನು ಯಾವುದರ ಬಗ್ಗೆ ಚಿಂತಿಸಬೇಕು?',
    prompt_unusual: 'ಕಳೆದ ಗಂಟೆಯ ಅಸಾಮಾನ್ಯ activity ತೋರಿಸಿ',
    prompt_health: 'ಪ್ರಸ್ತುತ network health ಸಾರಾಂಶ ನೀಡಿ',
  },
  ta: {
    download_report: 'அறிக்கையை பதிவிறக்கம் செய்க',
  },
  te: {
    download_report: 'నివేదిక డౌన్‌లోడ్ చేయండి',
  },
} satisfies Record<Language, Partial<Record<keyof typeof enStrings, string>>>;

export type StringKey = keyof typeof enStrings;

export function t(language: Language, key: StringKey, vars: Record<string, string | number> = {}) {
  const localized = strings[language] as Partial<Record<StringKey, string>>;
  const template = localized[key] || strings.en[key] || key;
  return Object.entries(vars).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template);
}
